import assert from 'node:assert/strict';
import fs from 'node:fs';

const html = fs.readFileSync(new URL('../admin.html', import.meta.url), 'utf8');

assert.match(html, /圖文卡設定與預覽/);
assert.match(html, /步驟 1[\s\S]*載入可推播會員/);
assert.match(html, /步驟 2[\s\S]*選擇會員/);
assert.match(html, /步驟 3[\s\S]*預覽這位會員的圖片卡/);
assert.match(html, /id="personalizedSingleBtn"[^>]*disabled/);
assert.match(html, /id="personalizedSendAllBtn"[^>]*hidden/);
assert.match(html, /節日背景生成器/);
assert.match(html, /使用節日範本/);
assert.match(html, /幫我自動生成/);
assert.match(html, /daily-peace-logo\.png/);
assert.match(html, /id="cardBlessingFont"/);
assert.match(html, /id="cardBlessingColor"/);
assert.match(html, /id="cardBlessingSize"/);
assert.match(html, /id="cardBlessingAlign"/);
assert.match(html, /id="cardBlessingPosition"/);
assert.doesNotMatch(html, /\.line-card-preview \.hero\s*\{[^}]*aspect-ratio:\s*4\s*\/\s*5/);
assert.match(html, /\.line-card-preview \.hero\s*\{[^}]*height:\s*auto/);
assert.match(html, /\.line-card-preview \.hero\s*\{[^}]*object-fit:\s*contain/);
assert.match(html, /id="cardButton5Label"[^>]*value="邀請親友成為守護人"/);
assert.match(html, /id="cardButton5Uri"[^>]*share-invite\.html/);
assert.match(html, /card-action-icon card-action-logo/);
assert.match(html, /card-action-icon card-action-shield/);
assert.match(html, /card-action-icon card-action-sos/);
assert.match(html, /card-action-icon card-action-bell/);
assert.match(html, /card-action-icon card-action-guardian/);
assert.match(html, /查看今日安心提醒/);
assert.match(html, /邀請親友成為守護人/);
assert.match(html, /#D4A017/i);
assert.match(html, /#A96508/i);
assert.match(html, /@media\s*\(max-width:\s*760px\)[\s\S]*card-editor-grid/);
console.log('admin personalized card editor behavior passed');
